esphome:
  name: uart-bridge
esp32:
  board: esp32dev

wifi:
  ssid: "Palo Alto Networks 2"
  password: "QWE$#@bvc642TYU"

logger:
  level: DEBUG

external_components:
- source: github://oxan/esphome-stream-server

debug:

uart:
  id: uart_bus
  tx_pin: GPIO17
  rx_pin: GPIO16
  baud_rate: 1_000_000
  rx_buffer_size: 2048
  debug:
    direction: BOTH
    dummy_receiver: false
    after:
      delimiter: "\n"
    sequence:
    - lambda: UARTDebug::log_string(direction, bytes);

stream_server:
  uart_id: uart_bus
  buffer_size: 2048

# socat -d -d pty,link=/tmp/vport1,raw,echo=0 TCP:uart-bridge.local:6638,tcp-nodelay
